set nocompatible              " required
filetype off                  " required
syntax on

" Change leader
let mapleader="\<Space>"

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Add all your plugins here (note older versions of Vundle used Bundle instead
" of Plugin)*

" Auto-Complete
Plugin 'Valloric/YouCompleteMe'

" Python autodindent
Plugin 'vim-scripts/indentpython.vim' " Indent python

" Syntax
" Plugin 'scrooloose/syntastic' "Syntax checker
Plugin 'w0rp/ale' "Replace syntastic

"
Plugin 'nvie/vim-flake8' " PEP8

" Colors
Plugin 'jnurmine/Zenburn' " Zenburn theme (console)
Plugin 'altercation/vim-colors-solarized' "Solarized theme (GUI)
Plugin 'lifepillar/vim-solarized8' "More recent Solarized theme

Plugin 'scrooloose/nerdtree' " Hierarchy tree

Plugin 'ctrlpvim/ctrlp.vim' " Search files

Plugin 'vim-airline/vim-airline' "Status bar
Plugin 'vim-airline/vim-airline-themes'

Plugin 'tpope/vim-fugitive' " Give Git command inside vim
Plugin 'junegunn/gv.vim' " Give a git browser

Plugin 'xolox/vim-misc' " Needed by vim-session
Plugin 'xolox/vim-session' " Make use of mksession easier

Plugin 'ludovicchabant/vim-gutentags' " Support tagv

Plugin 'saltstack/salt-vim' " For saltstack files

Plugin 'fatih/vim-go' " Go Plugin

Plugin 'pearofducks/ansible-vim' " Ansible plugin

" Rst related plugins
Plugin 'Rykka/riv.vim'
Plugin 'Rykka/InstantRst'

Plugin 'vim-scripts/csv.vim' " CSV column inside vim

Plugin 'vim-scripts/wmgraphviz' " graphviz plugin

Plugin 'plytophogy/vim-virtualenv' " Use virtualenv modules for all python

Plugin 'vim-scripts/plantuml-syntax' " Plantuml syntax highlighting

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
set encoding=utf-8

" Set filetype based on name
autocmd BufRead,BufNewFile *Dockerfile* setlocal filetype=dockerfile
autocmd BufRead,BufNewFile *dockerfile* setlocal filetype=dockerfile
autocmd BufRead,BufNewFile *.spec.in setlocal filetype=spec
autocmd BufRead,BufNewFile *.functions setlocal filetype=sh
autocmd BufRead,BufNewFile *.sls setlocal filetype=sls
autocmd BufRead,BufNewFile *.jinja setlocal filetype=jinja
" Prevent modelines to be run on commit message
" formatted like this "xxxx:"
autocmd FileType gitrebase setlocal nomodeline

"" General section
set nowrap        " don't wrap lines
set tabstop=4     " a tab is four spaces
set backspace=indent,eol,start
                    " allow backspacing over everything in insert mode
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set shiftwidth=4  " number of spaces to use for autoindenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,
                    "    case-sensitive otherwise
set smarttab      " insert tabs on the start of a line according to
                    "    shiftwidth, not tabstop
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set visualbell           " don't beep
set noerrorbells         " don't beep

" FX button mapping
set pastetoggle=<F2> " Toggle PASTE mode

" Remove trailing whitespaces
:nnoremap <silent> <F5> :let _s=@/ <Bar> :%s/\s\+$//e <Bar> :let @/=_s <Bar> :nohl <Bar> :unlet _s <CR>

set hidden " Allow leaving a buffer with unsaved changes

set mouse=a " Use mouse in all mode

set guioptions-=T  "remove toolbar

" Completion in menu bar
set wildmode=longest,list,full
set wildmenu

"" Remap
" <leader>sv sources .vimrc
nnoremap <leader>sv :source $MYVIMRC<CR>:runtime! plugin/settings/*<CR>:redraw<CR>:echo $MYVIMRC 'reloaded'<CR>

" Buffer navigation
nnoremap <silent> <leader><Left> <esc>:bp<CR>
nnoremap <silent> <leader><Right> <esc>:bn<CR>

" Split navigations
nnoremap <silent> <C-Right> <c-w>l
nnoremap <silent> <C-Left> <c-w>h
nnoremap <silent> <C-Up> <c-w>k
nnoremap <silent> <C-Down> <c-w>j

" cnext/cprev navigation
nnoremap <silent> <leader><PageUp> <esc>:cnext<CR>
nnoremap <silent> <leader><PageDown> <esc>:cprev<CR>

" Copy to system clipboard Visual selection
" vnoremap <silent> <C-c> y/<C-R>"*<CR><esc>

" Set a border at 80 column
set colorcolumn=80

" Autocompletion stuff
let g:ycm_autoclose_preview_window_after_completion=1
let g:ycm_collect_identifiers_from_tags_files = 1 " Use ctags
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>
map <leader>gd :YcmCompleter GetDoc<CR>

set background=dark

" Colors set
if has('gui_running')
  colorscheme solarized8
  set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 9
else
  "colors theme configuration (console)
  if &term == "linux" || &term == "screen.linux"
    set t_Co=8
    colorscheme solarized8
  elseif &term == "screen-256color"
    set term=xterm-256color
    set t_Co=256
    colorscheme solarized8
  else
    set t_Co=256
    colorscheme solarized8
  endif
endif

"" NerdTree
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree
nnoremap <leader>n :NERDTreeToggle<CR>
" Close vim if only NerdTree is open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Always enable status bar
set laststatus=2

" Use powerline font symbols
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"

" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1

" spaces are allowed after tabs, but not in between
" this algorithm works well with programming styles that use tabs for
" indentation and spaces for alignment
let g:airline#extensions#whitespace#mixed_indent_algo = 2

" Session
let g:session_autosave = "yes"
let g:session_autosaveperiodic = 60
let g:session_persist_colors = 0
let g:session_persist_font = 0

" Refresh correctly background color upon vim console exit
":set t_te=[H2J

"""""""""""""""""""""
" ctags related stuff
"""""""""""""""""""""
" Search for ".tags" in current directory and go up inside the hierarchy
" if not found
set tags=./.tags;

" Easytags settings
" let g:easytags_dynamic_files = 2
" set cpoptions+=d
" let g:easytags_async = 1

" Gutentags settings
let g:gutentags_ctags_tagfile = ".tags"
set statusline+=%{gutentags#statusline()} "Display something while generating

" Set python ALE linters
let g:ale_linters = {'python': ['flake8']}

" Disable Riv Folding
let g:riv_disable_folding = 1
