export GOROOT="$HOME/go"
[ -d "$GOROOT" ] || mkdir -p "$GOROOT"
[ -d "$GOROOT"/bin ] &&  export PATH="$GOROOT"/bin:"$PATH"
export GOPATH="$GOROOT/work"
[ -d "$GOPATH" ] || mkdir -p "$GOPATH"
export PATH="$GOPATH"/bin:"$PATH"
